name: 8-Reusable 
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: true
        default: dist
        type: string
    # secrets:
    #   some-secret:
    #     required: false
    outputs:
      result:
        description: The result of the deployment operation
        value: ${{ jobs.deploy-inside.outputs.outcome }}
jobs:
  deploy-inside:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List artifact files
        run: ls
      - name: Output information
        run: echo 'Deploy information'
      - name: Set result output
        id: set-result
        # run: echo "::set-output name=step-result::success"
        run: echo "step-result=success" >> $GITHUB_OUTPUT 


        