name: 9-Own-actions
on:
  push:
    branches:
      - master
  workflow_dispatch:

  workflow_call:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load and cache dependencies
        id: cache-deps
        # uses: ./.github/actions/cached-deps
        # uses: sebasnaatwo/pruebas/.github/actions/cached-deps@master

        uses: sebasnaatwo/pruebas/.github/actions@master
        with:
          caching: 'false'
      - name: Is cache used from Load and cache dependencies
        run: echo "Cache is used ? ${{ steps.cache-deps.outputs.used-cache }}"
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load and cache dependencies
        uses: ./.github/actions/cached-deps
      - name: Test code
        id: run-tests
        run: npm run test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    # environment: testing
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Load and cache dependencies
        uses: ./.github/actions/cached-deps
      - name: Build website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    # environment: pro
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
          path: ./dist
      - name: Output contents
        run: ls
      - name: Deploy site
        id: deploy
        # uses: ./.github/actions/deploy-s3-javascript
        # uses: ./.github/actions/deploy-s3-docker
        uses: sebasnaa/deploy-s3-docker@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          bucket: sebasnaa-custom-hosting
          dist-folder: ./dist
          # bucket-region: 'eu-west-3'
      - name: Show Website URL
        run: |
          echo "Live URL ${{ steps.deploy.outputs.webUrl }}"



  # information:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get code
  #       uses: actions/checkout@v3
  #     - name: Run custom actions from js script
  #       uses: ./.github/actions/deploy-s3-javascript