name: Call_Secondary_Workflow

on:
  workflow_dispatch:
    inputs:
      param1:
        description: 'Parameter 1'
        required: false
        default: 'default_value_param1'
        type: string
      param2:
        description: 'Parameter 2'
        required: false
        default: 'default_value_param2'
        type: string
  workflow_call:
    inputs:
      param1:
        description: 'Parameter 1'
        required: true
        type: string
      param2:
        description: 'Parameter 2'
        required: true
        type: string

jobs:
  secondary-job:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Use Parameters in Secondary Job
        run: echo "Running secondary job with param1=${{ inputs.param1 }} and param2=${{ inputs.param2 }}"

  deploy:
    uses: ./.github/workflows/8-Reusable.yml
    with:
      artifact-name: dist-files
