name: Call Secondary Workflow

on:
  workflow_call:
    inputs:
      param1: null
      param2: null

jobs:
  secondary-job:
    runs-on: ubuntu-latest

    steps:
      - name: Use Parameters in Secondary Job
        run: echo "Running secondary job with param1=${{ inputs.param1 }} and param2=${{ inputs.param2 }}"
