name: Call_Secondary_Workflow

on:
  workflow_dispatch:
    inputs:
      param1: ''
      param2: ''
  workflow_call:
    inputs:
      param1: ''
      param2: ''

jobs:
  secondary-job:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Use Parameters in Secondary Job
        run: echo "Running secondary job with param1=${{ inputs.param1 }} and param2=${{ inputs.param2 }}"
