name: EchoWorkflow

on:
  # workflow_call:
  #   inputs:
  #     param1:
  #       description: 'Parameter 1'
  #       required: false
  #       default: 'default_value_param1'
  #       type: string

  workflow_dispatch:
    inputs:
      param1:
        description: 'Parameter 1'
        required: false
        default: 'default_value_param1'
        type: string

jobs:
  echo_input:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Input
        run: echo "Input received: ${{ inputs.input_value }}"