name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      param1-values:
        description: 'Values for param1'
        required: false
        # default: 'Sebas,Pepe,Felipe'
        default: 'Sebas'

jobs:
  main-job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        param1: ${{ split(inputs.param1-values, ',') }}
    steps:
      - name: pruebas
        run: echo "hola"
  
  deploy:
    uses: ./.github/workflows/final_workflow.yml
    with:
      param1: dist-files

    # steps:
    #   - name: Trigger Secondary Workflow
    #     run: |
    #       for value in "${{ matrix.param1 }}"; do
    #         curl -L \
    #           -X POST \
    #           -H "Accept: application/vnd.github+json" \
    #           -H "Authorization: Bearer ${{ secrets.SEBAS_ACC }}" \
    #           -H "X-GitHub-Api-Version: 2022-11-28" \
    #           https://api.github.com/repos/sebasnaa/tmp-presentacion/actions/workflows/final_workflow.yml/dispatches \
    #           -d "{\"ref\":\"master\",\"inputs\":{\"param1\":\"${value}\"}}"
    #       done
