name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Secondary Workflow
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.SEBAS_ACC }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/sebasnaa/tmp-presentacion/actions/workflows/Call_Secondary_Workflow.yml/dispatches \
            -d '{"ref":"master","inputs":{"param1":"Mona the Octocat","param2":"San Francisco, CA"}}'




    




