name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Secondary Workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: Bearer ${{ secrets.SEBAS_ACC }}" \
            "https://api.github.com/repos/sebasnaa/tmp-presentacion/dispatches" \
            -d '{"event_type": "Call_Secondary_Workflow", "client_payload": {"param1": "value1", "param2": "value2"}}'




    




