name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  define:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
        param1: ['value1', 'value2', 'value3']
        param2: ['valueA', 'valueB', 'valueC']

  main-job:
    needs: define
    uses: sebasnaa/tmp-presentacion/.github/workflows/call-secondary-workflow/action.yml@master
    with:
      param1: ${{ matrix.param1 }}
      param2: ${{ matrix.param2 }}



    




